spring:
  application:
    name: micro-consumer-movie-ribbon-properties-customizing
server:
  port: 8010
user: 
  userServicePath: http://localhost:7900/simple/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
micro-consumer-movie-ribbon-properties-customizing: 
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule